
name: Deploy Flutter Web to GitHub Pages


on:
  push:
    branches: [ "main" ]


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4 

      - name: 2. Setup do Flutter
        uses: subosito/flutter-action@v2 
        with:
          channel: 'stable'

      - name: 3. Build da versão web
        run: flutter build web --release --base-href /diailog/ --dart-define=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
        
        

      - name: 4. Upload do artefato para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web 

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no GitHub Pages
        uses: actions/deploy-pages@v4 
